local opt = vim.opt

opt.helplang = 'ja'
opt.smartcase = true
opt.splitright = true
opt.termguicolors = true
opt.hidden = true
opt.updatetime = 300
opt.expandtab = true
opt.termguicolors = true
opt.autoindent = true
opt.smartindent = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.autoread = true
opt.number = true
opt.relativenumber = true
opt.signcolumn = 'yes'
opt.cursorline = true
